version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - db-auth:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth-user
    restart: always

  adminer:
    image: adminer:4.8.1
    ports:
      - "127.0.0.1:3002:3002"
    restart: always

volumes:
  db-auth: { }

